import client from "./client";

const financeApi = {
  getCategories:        ()        => client.get("/finance/categories"),
  createCategory:       (data)    => client.post("/finance/categories", data),
  getStructures:        ()        => client.get("/finance/structures"),
  createStructure:      (data)    => client.post("/finance/structures", data),
  updateStructure:      (id,data) => client.put(`/finance/structures/${id}`, data),
  deleteStructure:      (id)      => client.delete(`/finance/structures/${id}`),
  getInvoices:          (params)  => client.get("/finance/invoices", { params }),
  createInvoice:        (data)    => client.post("/finance/invoices", data),
  updateInvoice:        (id,data) => client.put(`/finance/invoices/${id}`, data),
  bulkGenerate:         (data)    => client.post("/finance/invoices/bulk", data),
  generateMonthly:      (month)   => client.post("/finance/invoices/generate-monthly", month ? { month } : {}),
  getAutoGenerateSettings:    ()      => client.get("/finance/auto-generate-settings"),
  updateAutoGenerateSettings: (data)  => client.put("/finance/auto-generate-settings", data),
  runAutoGenerateNow:         ()      => client.post("/finance/auto-generate-settings/run-now"),
  downloadInvoicePdf:   (id)      => client.get(`/finance/invoices/${id}/pdf`, { responseType:"blob" }),
  getPayments:          (params)  => client.get("/finance/payments", { params }),
  getInvoicePayments:   (id)      => client.get(`/finance/invoices/${id}/payments`),
  searchCharges:        (params)  => client.get("/finance/charges/search", { params }),
  waiveCharge:          (itemId)  => client.post(`/finance/charges/${itemId}/waive`),
  recordPayment:        (data)    => client.post("/finance/payments", data),
  getDashboard:         ()        => client.get("/finance/dashboard"),
  downloadPaymentReceipt: (id) => client.get(`/finance/payments/${id}/receipt`, { responseType:"blob" }),
  getFeeTypes:             ()       => client.get("/finance/fee-types"),
  createFeeType:           (data)   => client.post("/finance/fee-types", data),
  updateFeeType:           (id,data)=> client.put(`/finance/fee-types/${id}`, data),
  deleteFeeType:           (id)     => client.delete(`/finance/fee-types/${id}`),
  getClassFees:            (params) => client.get("/finance/class-fees", { params }),
  createClassFee:          (data)   => client.post("/finance/class-fees", data),
  deleteClassFee:          (id)     => client.delete(`/finance/class-fees/${id}`),
  getDiscountConfig:       ()       => client.get("/finance/discount-config"),
  saveDiscountConfig:      (data)   => client.put("/finance/discount-config", data),
  getClassFeeConfigs:       ()       => client.get("/finance/class-fee-config"),
  saveClassFeeConfig:       (data)   => client.post("/finance/class-fee-config", data),
  deleteClassFeeConfig:     (id)     => client.delete(`/finance/class-fee-config/${id}`),
  getFeeCharges:            ()       => client.get("/finance/charges"),
  createFeeCharge:          (data)   => client.post("/finance/charges", data),
  updateFeeCharge:          (id,data)=> client.put(`/finance/charges/${id}`, data),
  deleteFeeCharge:          (id)     => client.delete(`/finance/charges/${id}`),
  generateSmartMonthly:     (data)   => client.post("/finance/invoices/generate-smart-monthly", data),
  getChargeTypes:           ()       => client.get("/finance/charge-types"),
  createChargeType:         (data)   => client.post("/finance/charge-types", data),
  updateChargeType:         (id, data) => client.put("/finance/charge-types/" + id, data),
  toggleChargeType:         (id)     => client.put("/finance/charge-types/" + id + "/toggle"),
  verifyPayment:        (id)      => client.put(`/finance/payments/${id}/verify`),
  getStudentSummary:    (id)      => client.get(`/finance/student/${id}`),
  getLockedAccounts:        (params) => client.get("/finance/locked-accounts", { params }),
  getFeeReportSchool:       (params) => client.get("/finance/reports/fee-report", { params }),
  getFeeReportMyClass:      (params) => client.get("/finance/reports/fee-report/my-class", { params }),
  getFeeReportMyChild:      ()       => client.get("/finance/reports/fee-report/my-child"),
  getFeeReportMe:           ()       => client.get("/finance/reports/fee-report/me"),
  getMyClassLockedAccounts: (params) => client.get("/finance/locked-accounts/my-class", { params }),
  unlockAccount:            (studentId) => client.post(`/finance/unlock-account/${studentId}`),
};

export default financeApi;